const fakeDetail = {
  vegetarian: true,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: true,
  cheap: false,
  veryPopular: true,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 15,
  gaps: 'no',
  preparationMinutes: 5,
  cookingMinutes: 0,
  aggregateLikes: 689,
  healthScore: 63,
  creditsText: 'Jen West',
  sourceName: 'Pink When',
  pricePerServing: 204.29,
  extendedIngredients: [],
  id: 715497,
  title: 'Berry Banana Breakfast Smoothie',
  readyInMinutes: 5,
  servings: 1,
  sourceUrl:
    'http://www.pinkwhen.com/berry-banana-breakfast-smoothie/',
  image: 'https://spoonacular.com/recipeImages/715497-556x370.jpg',
  imageType: 'jpg',
  nutrition: {
    nutrients: [
      {
        name: 'Calories',
        amount: 440.37,
        unit: 'kcal',
        percentOfDailyNeeds: 22.02,
      },
      {
        name: 'Fat',
        amount: 9.87,
        unit: 'g',
        percentOfDailyNeeds: 15.19,
      },
      {
        name: 'Saturated Fat',
        amount: 2.68,
        unit: 'g',
        percentOfDailyNeeds: 16.75,
      },
      {
        name: 'Carbohydrates',
        amount: 68.79,
        unit: 'g',
        percentOfDailyNeeds: 22.93,
      },
      {
        name: 'Net Carbohydrates',
        amount: 64.75,
        unit: 'g',
        percentOfDailyNeeds: 23.54,
      },
      {
        name: 'Sugar',
        amount: 49.99,
        unit: 'g',
        percentOfDailyNeeds: 55.55,
      },
      {
        name: 'Cholesterol',
        amount: 11.35,
        unit: 'mg',
        percentOfDailyNeeds: 3.78,
      },
      {
        name: 'Sodium',
        amount: 400.72,
        unit: 'mg',
        percentOfDailyNeeds: 17.42,
      },
      {
        name: 'Protein',
        amount: 20.42,
        unit: 'g',
        percentOfDailyNeeds: 40.84,
      },
      {
        name: 'Vitamin C',
        amount: 64.41,
        unit: 'mg',
        percentOfDailyNeeds: 78.07,
      },
      {
        name: 'Calcium',
        amount: 747.77,
        unit: 'mg',
        percentOfDailyNeeds: 74.78,
      },
      {
        name: 'Vitamin B12',
        amount: 3.75,
        unit: 'µg',
        percentOfDailyNeeds: 62.53,
      },
      {
        name: 'Vitamin B2',
        amount: 1.02,
        unit: 'mg',
        percentOfDailyNeeds: 59.83,
      },
      {
        name: 'Vitamin B3',
        amount: 9.3,
        unit: 'mg',
        percentOfDailyNeeds: 46.48,
      },
      {
        name: 'Vitamin B6',
        amount: 0.84,
        unit: 'mg',
        percentOfDailyNeeds: 42.17,
      },
      {
        name: 'Vitamin E',
        amount: 6.24,
        unit: 'mg',
        percentOfDailyNeeds: 41.59,
      },
      {
        name: 'Phosphorus',
        amount: 372.38,
        unit: 'mg',
        percentOfDailyNeeds: 37.24,
      },
      {
        name: 'Folate',
        amount: 134.47,
        unit: 'µg',
        percentOfDailyNeeds: 33.62,
      },
      {
        name: 'Potassium',
        amount: 1109.7,
        unit: 'mg',
        percentOfDailyNeeds: 31.71,
      },
      {
        name: 'Selenium',
        amount: 17.21,
        unit: 'µg',
        percentOfDailyNeeds: 24.59,
      },
      {
        name: 'Vitamin A',
        amount: 1057.73,
        unit: 'IU',
        percentOfDailyNeeds: 21.15,
      },
      {
        name: 'Vitamin B1',
        amount: 0.32,
        unit: 'mg',
        percentOfDailyNeeds: 21.08,
      },
      {
        name: 'Zinc',
        amount: 3,
        unit: 'mg',
        percentOfDailyNeeds: 19.97,
      },
      {
        name: 'Copper',
        amount: 0.39,
        unit: 'mg',
        percentOfDailyNeeds: 19.48,
      },
      {
        name: 'Manganese',
        amount: 0.39,
        unit: 'mg',
        percentOfDailyNeeds: 19.41,
      },
      {
        name: 'Vitamin D',
        amount: 2.83,
        unit: 'µg',
        percentOfDailyNeeds: 18.88,
      },
      {
        name: 'Magnesium',
        amount: 67.61,
        unit: 'mg',
        percentOfDailyNeeds: 16.9,
      },
      {
        name: 'Fiber',
        amount: 4.04,
        unit: 'g',
        percentOfDailyNeeds: 16.16,
      },
      {
        name: 'Vitamin B5',
        amount: 1.47,
        unit: 'mg',
        percentOfDailyNeeds: 14.68,
      },
      {
        name: 'Iron',
        amount: 2.53,
        unit: 'mg',
        percentOfDailyNeeds: 14.08,
      },
      {
        name: 'Vitamin K',
        amount: 2,
        unit: 'µg',
        percentOfDailyNeeds: 1.9,
      },
    ],
    properties: [],
    flavonoids: [],
    ingredients: [],
    caloricBreakdown: {},
    weightPerServing: {},
  },
  summary:
    'If you have around <b>5 minutes</b> to spend in the kitchen, Berry Banana Breakfast Smoothie might be a tremendous <b>lacto ovo vegetarian</b> recipe to try. This recipe makes 1 servings with <b>501 calories</b>, <b>21g of protein</b>, and <b>11g of fat</b> each. For <b>$2.19 per serving</b>, this recipe <b>covers 32%</b> of your daily requirements of vitamins and minerals. 688 people found this recipe to be tasty and satisfying. It is brought to you by Pink When. Head to the store and pick up graham crackers, soy milk, banana, and a few other things to make it today. It works well as a morn meal. Overall, this recipe earns a <b>super spoonacular score of 100%</b>. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-249239">Berry Banana Breakfast Smoothie</a>, <a href="https://spoonacular.com/recipes/berry-and-banana-oat-breakfast-smoothie-626817">Berry and Bananan Oat Breakfast Smoothie</a>, and <a href="https://spoonacular.com/recipes/berry-breakfast-smoothie-774875">Berry Breakfast Smoothie</a>.',
  cuisines: [],
  dishTypes: ['morning meal', 'brunch', 'breakfast'],
};

export default fakeDetail;
